//
//  TrailWidgetPlaceholderBasemaps.swift
//  OpenWidget
//
//  GENERATED by Scripts/placeholder-basemaps.sh — do not edit by hand.
//
//  The map the widget gallery and the Xcode previews draw under the
//  placeholder trail. A real trail's basemaps are rendered by the app into
//  the App Group; the placeholder is not a real trail, so its four images
//  are rendered ahead of time and shipped in the widget's asset catalogue
//  instead. See that script's header, and `TrailWidgetPlaceholder.swift`
//  for the route these frame.
//
//  `fileName` names an `NSDataAsset` here rather than a file in the App
//  Group's basemap directory, which is the whole of the difference: every
//  other field means exactly what it means for a rendered set, and
//  `TrailWidgetBasemapImages` is the reader that tells the two apart.
//

import Foundation
import OpenHikesShared

enum TrailWidgetPlaceholderBasemaps {
    /// The `hikeID` below. A literal rather than a fresh `UUID()` per run
    /// of the generator, so a re-render is a diff of the numbers that
    /// actually moved.
    private static let hikeID = UUID(
        uuidString: "72C096C0-D02C-425B-A0AA-906586C4E92A"
    ) ?? UUID()

    /// The set as `TrailMapView` wants it, reading from the widget's asset
    /// catalogue rather than from the App Group.
    ///
    /// Its `hikeID` is never compared against the placeholder snapshot's,
    /// which is a fresh `UUID()` per process. The field exists because a
    /// *rendered* set has to name the trail it frames —
    /// `SharedStore.loadBasemapSet(for:)` refuses one that does not — and
    /// nothing here goes near the store.
    static let set = TrailBasemapSet(
        hikeID: hikeID,
        coverage: UnitMercatorRect(
            originX: 0.536077777778,
            originY: 0.349274733255,
            width: 8.19444444444e-05,
            height: 5.14859219036e-05
        ),
        images: [
            TrailBasemap(
                fileName: "PlaceholderBasemapSquareDark",
                variant: .square,
                appearance: .dark,
                pixelWidth: 640,
                pixelHeight: 640,
                visibleRect: UnitMercatorRect(
                    originX: 0.536065486111,
                    originY: 0.349247212327,
                    width: 0.000106527777778,
                    height: 0.000106527777778
                )
            ),
            TrailBasemap(
                fileName: "PlaceholderBasemapSquareLight",
                variant: .square,
                appearance: .light,
                pixelWidth: 640,
                pixelHeight: 640,
                visibleRect: UnitMercatorRect(
                    originX: 0.536065486111,
                    originY: 0.349247212327,
                    width: 0.000106527777778,
                    height: 0.000106527777778
                )
            ),
            TrailBasemap(
                fileName: "PlaceholderBasemapWideDark",
                variant: .wide,
                appearance: .dark,
                pixelWidth: 760,
                pixelHeight: 360,
                visibleRect: UnitMercatorRect(
                    originX: 0.536048099874,
                    originY: 0.349267010366,
                    width: 0.000141300252336,
                    height: 6.69316984747e-05
                )
            ),
            TrailBasemap(
                fileName: "PlaceholderBasemapWideLight",
                variant: .wide,
                appearance: .light,
                pixelWidth: 760,
                pixelHeight: 360,
                visibleRect: UnitMercatorRect(
                    originX: 0.536048099874,
                    originY: 0.349267010366,
                    width: 0.000141300252336,
                    height: 6.69316984747e-05
                )
            ),
        ]
    )
}
