//
//  AppVersion.swift
//  OpenHikes
//
//  Which build this is, read from the bundle rather than written down.
//
//  Two things need it and for a while only one of them had it. The tile and
//  Overpass User-Agent has announced the marketing version since it stopped
//  being a literal — a literal being a second place the version lives and the
//  one nobody remembers to bump. The other is a person: `AboutSection` asks
//  hikers to report an issue on GitHub, and until this existed nothing in the
//  app told them which build they were reporting about.
//

import Foundation

/// The running build's version, as the App Store and a `v…` tag spell it.
///
/// Both keys are generated by Xcode from `MARKETING_VERSION` and
/// `CURRENT_PROJECT_VERSION` for every target here, so neither fallback is
/// reachable from one of them — see `InfoPlistContractTests`, which asserts
/// that against `Bundle.main` rather than against this type. The fallbacks
/// exist because a `Bundle` is not required to carry either key, and a screen
/// that crashed rather than said "unknown" would be a worse answer to "what
/// version is this".
nonisolated enum AppVersion {
    /// `CFBundleShortVersionString` — what the App Store calls the version,
    /// and the first half of the `v<marketing>-<build>` tag an archived build
    /// is tagged with.
    static let marketing = Bundle.main
        .object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0"

    /// `CFBundleVersion` — the build number, which is what actually
    /// distinguishes two TestFlight builds of the same version.
    static let build = Bundle.main
        .object(forInfoDictionaryKey: "CFBundleVersion") as? String

    /// `1.0 (26)`, or just the marketing version where there is no build
    /// number to add.
    static var display: String {
        guard let build else { return marketing }
        return "\(marketing) (\(build))"
    }
}
